### ISSUE TITLE
Schematic shows VSS connected to midpoint of divider

### ISSUE THREAD

**Issue by agittins** [ardyesp/PowerMeter#1]
I'm a bit confused by the schematic, it shows VSS being connected to the mid-point of the voltage divider, along with one leg of each CT. Is VSS meant to connect to the GND pin of the regulator instead, or am I misinterpreting something?

**Comment by ardyesp** [comment]
No, it should not be connected to the ground pin of the regulator. This is to prevent negative voltage swings - as described briefly in the readme.

**Comment by agittins** [comment]
I'm still confused, sorry - I get that the two voltage dividers add a DC bias of vcc/2 to the CT and voltage sense inputs in order to keep them within vcc and the regulator's GND, but then the nrf's ground is tied to vcc/2 as well, so won't it see negative swings due to that? How does tying the mcu's ground to vcc/2 work here?

The readme's description implies that the mcu would be referenced to GND and VCC, so that the analog inputs are biased to vcc/2 to avoid negative swings, but with the mcu's VSS tied to vcc/2 I can't understand how that would work.

I feel like either there's an error in the schematic or I am missing some element of the circuit in my analysis. So when the CT has one leg connected to vcc/2, the other leg will swing above and below vcc/2 - which with respect to the regulator's ground will always be positive (if the swing does not exceed +/- vcc/2). But in respect to vcc/2, the CT's voltage will swing between vcc/2 and -vcc/2. With the mcu's VSS connected to vcc/2, this means the analog inputs will be reverse-biased during the negative swing of each cycle. I might be missing something obvious here, I just can't see it. :-/

**Comment by ardyesp** [comment]
Ok I see what you are saying. Yes the schematic is incorrect and the GND pin of nrf should be connected to system ground which is the GND pin of the regulator. I will update the schematic to fix this.
